//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekomsys.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public string BannerId { get; set; }
        public string BannerGroup { get; set; }
        public string NavigateUrl { get; set; }
        public string ImageUrl { get; set; }
        public System.DateTime Entered { get; set; }
        public System.DateTime Updated { get; set; }
        public int Hits { get; set; }
        public int MaxHits { get; set; }
        public int ResetHits { get; set; }
        public int Clicks { get; set; }
        public int ResetClicks { get; set; }
        public bool Active { get; set; }
        public int SortOrder { get; set; }
        public string Type { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int BannerType { get; set; }
    }
}
