//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekomsys.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DevSamplesEntities : DbContext
    {
        public DevSamplesEntities()
            : base("name=DevSamplesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_News> tb_News { get; set; }
        public DbSet<tb_Page> tb_Page { get; set; }
        public DbSet<tb_User_UserType_Mapping> tb_User_UserType_Mapping { get; set; }
        public DbSet<tb_Users> tb_Users { get; set; }
        public DbSet<tb_UserType> tb_UserType { get; set; }
        public DbSet<tb_Contact> tb_Contact { get; set; }
        public DbSet<tb_Page> tb_Page { get; set; }
    
        public virtual ObjectResult<Nullable<int>> usp_CheckLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_CheckLogin", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<usp_getOfficeDetails_Result> usp_getOfficeDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getOfficeDetails_Result>("usp_getOfficeDetails");
        }
    
        public virtual ObjectResult<usp_GetAllPages_SubPages_Result> usp_GetAllPages_SubPages()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAllPages_SubPages_Result>("usp_GetAllPages_SubPages");
        }
    }
}
